Repository afairgiant/MediKeep, pull requests merged in 2025-08, with the labels that each got.

#144 Enhance Backup Management with Improved Notification System
  frontend/src/components/backup/ProgressNotification.js
  frontend/src/hooks/useBackupNotifications.js
  frontend/src/pages/admin/BackupManagement.js
Labels: enhancement

#145 feat: Implement Enhanced Activity Tracking System
  frontend/src/App.js
  frontend/src/config/activityConfig.js
  frontend/src/contexts/AuthContext.js
  frontend/src/hooks/ACTIVITY_TRACKING.md
  frontend/src/hooks/index.js
  frontend/src/hooks/useActivityTracker.js
  frontend/src/hooks/useActivityTracker.test.js
  frontend/src/services/apiClient.js
  frontend/src/utils/secureActivityLogger.js
  frontend/src/utils/throttleUtils.js
Labels: enhancement

#148 feat: Implement file viewing
  PAPERLESS_DUPLICATE_DETECTION.md
  SYNC_DEBUG_IMPLEMENTATION_SUMMARY.md
  SYNC_STATUS_DEBUG_GUIDE.md
  app/api/deps.py
  app/api/v1/endpoints/entity_file.py
  app/services/generic_entity_file_service.py
  docs/LOG_ROTATION.md
  frontend/src/App.js
  frontend/src/components/shared/DocumentManager.js
  frontend/src/components/shared/DocumentManagerCore.js
  frontend/src/components/shared/DocumentManagerWithProgress.js
  frontend/src/components/shared/FileList.js
  frontend/src/components/shared/RenderModeContent.js
  frontend/src/hooks/useActivityTracker.js
  frontend/src/pages/Dashboard.js
  frontend/src/services/api/index.js
  frontend/src/utils/activityNavigation.js
  frontend/src/utils/throttleUtils.js
Labels: enhancement

#149 Bug activity tracker
  frontend/src/App.js
  frontend/src/utils/secureActivityLogger.js
Labels: bug

#152 feat: Enhance user model update process with safety checks
  frontend/src/pages/admin/ModelEdit.js
Labels: bug, enhancement

#156 Bug: Fixed error logic for document viewing
  frontend/src/constants/errorMessages.js
  frontend/src/services/api/index.js
Labels: bug

#158 Page standarization
  alembic/migrations/versions/20250803_1857_bdb4d433f547_add_medication_id_to_conditions_table.py
  app/api/v1/endpoints/condition.py
  app/models/models.py
  app/schemas/condition.py
  frontend/src/components/medical/MedicationRelationships.js
  frontend/src/components/medical/VitalsList.js
  frontend/src/components/medical/allergies/AllergyCard.js
  frontend/src/components/medical/allergies/AllergyFormWrapper.js
  frontend/src/components/medical/allergies/AllergyViewModal.js
  frontend/src/components/medical/allergies/index.js
  frontend/src/components/medical/base/BaseMedicalCard.js
  frontend/src/components/medical/conditions/ConditionCard.js
  frontend/src/components/medical/conditions/ConditionFormWrapper.js
  frontend/src/components/medical/conditions/ConditionViewModal.js
  frontend/src/components/medical/conditions/index.js
  frontend/src/components/medical/family-history/FamilyHistoryCard.js
  frontend/src/components/medical/family-history/FamilyHistoryFormWrapper.js
  frontend/src/components/medical/family-history/FamilyHistoryViewModal.js
  frontend/src/components/medical/family-history/index.js
  frontend/src/components/medical/immunizations/ImmunizationCard.js
  frontend/src/components/medical/immunizations/ImmunizationFormWrapper.js
  frontend/src/components/medical/immunizations/ImmunizationViewModal.js
  frontend/src/components/medical/immunizations/index.js
  frontend/src/components/medical/medications/MedicationCard.js
  frontend/src/components/medical/medications/MedicationFormWrapper.js
  frontend/src/components/medical/medications/MedicationViewModal.js
  frontend/src/components/medical/medications/index.js
  frontend/src/components/medical/patient-info/PatientFormWrapper.js
  frontend/src/components/medical/pharmacy/PharmacyCard.js
  frontend/src/components/medical/pharmacy/PharmacyFormWrapper.js
  frontend/src/components/medical/pharmacy/PharmacyViewModal.js
  frontend/src/components/medical/practitioners/PractitionerCard.js
  frontend/src/components/medical/practitioners/PractitionerFormWrapper.js
  frontend/src/components/medical/practitioners/PractitionerViewModal.js
  frontend/src/components/medical/treatments/TreatmentCard.js
  frontend/src/components/medical/treatments/TreatmentFormWrapper.js
  frontend/src/components/medical/treatments/TreatmentViewModal.js
  frontend/src/components/medical/vital/VitalCard.js
  frontend/src/components/medical/vital/VitalFormWrapper.js
  frontend/src/components/medical/vital/VitalViewModal.js
  frontend/src/pages/medical/Allergies.js
  frontend/src/pages/medical/Conditions.js
  frontend/src/pages/medical/FamilyHistory.js
  frontend/src/pages/medical/Immunization.js
  frontend/src/pages/medical/Medication.js
  frontend/src/pages/medical/Patient-Info.js
  frontend/src/pages/medical/Pharmacies.js
  frontend/src/pages/medical/Practitioners.js
  frontend/src/pages/medical/Treatments.js
  frontend/src/pages/medical/Vitals.js
  frontend/src/services/api/index.js
  frontend/src/utils/medicalFormFields.js
Labels: enhancement

#160 Paperless 2fa
  app/api/v1/endpoints/entity_file.py
  app/api/v1/endpoints/paperless.py
  app/schemas/user_preferences.py
  app/services/generic_entity_file_service.py
  app/services/paperless_auth.py
  app/services/paperless_client.py
  app/services/paperless_service.py
  app/services/paperless_task_resolver.py
  frontend/src/components/settings/ConnectionConfigCard.js
  frontend/src/components/settings/PaperlessSettings.js
  frontend/src/components/shared/DocumentManager.js
  frontend/src/components/shared/DocumentManagerCore.js
  frontend/src/components/shared/FileList.js
  frontend/src/constants/paperlessSettings.js
  frontend/src/services/api/index.js
  frontend/src/services/api/paperlessApi.js
  frontend/src/styles/components/PaperlessSettings.css
  tests/unit/test_paperless_service.py
Labels: bug

#161 Bug: Support API token authentication for paperless uploads and connection persistence
  app/api/v1/endpoints/paperless.py
  app/core/config.py
  app/services/generic_entity_file_service.py
  frontend/src/components/settings/PaperlessSettings.js
Labels: bug

#163 Bug: Various Bug Fixes
  app/api/v1/endpoints/emergency_contact.py
  app/api/v1/endpoints/paperless.py
  app/schemas/condition.py
  app/services/generic_entity_file_service.py
  frontend/src/components/medical/allergies/AllergyCard.js
  frontend/src/components/medical/immunizations/ImmunizationFormWrapper.js
  frontend/src/components/medical/visits/VisitFormWrapper.js
  frontend/src/components/shared/DocumentManagerCore.js
  frontend/src/hooks/useMedicalData.js
  frontend/src/pages/medical/EmergencyContacts.js
  frontend/src/pages/medical/Procedures.js
  frontend/src/pages/medical/Treatments.js
  frontend/src/pages/medical/Visits.js
  frontend/src/services/api/index.js
  frontend/src/services/api/paperlessApi.js
  frontend/src/utils/errorMessageUtils.js
Labels: bug, enhancement

#164 Bug: Enhance Paperless file handling and filename correction
  app/api/v1/endpoints/entity_file.py
  app/core/config.py
  app/services/generic_entity_file_service.py
  frontend/src/services/api/index.js
Labels: bug

#173 Bug: Condition date pickers fix.
  frontend/src/components/medical/conditions/ConditionFormWrapper.js
  frontend/src/hooks/useApi.js
  frontend/src/pages/medical/Conditions.js
  frontend/src/services/api/index.js
  frontend/src/utils/dateUtils.js
  frontend/src/utils/errorUtils.js
Labels: bug

#174 Bug: Phone symbol handling
  app/core/config.py
  frontend/src/components/adapters/FormInput.js
  frontend/src/components/medical/BaseMedicalForm.js
  frontend/src/components/navigation/DesktopNavigation.js
  frontend/src/config/navigation.config.js
  frontend/src/pages/medical/Conditions.js
  frontend/src/utils/dateUtils.js
  frontend/src/utils/errorUtils.js
  frontend/src/utils/phoneUtils.js
Labels: bug

#177 Simplify top menus
  frontend/src/components/adapters/PageHeader.js
Labels: enhancement

#181 Feature: SSO
  README.md
  alembic/migrations/versions/20250812_1400_eb5cb4aa35d5_add_sso_support_to_users.py
  alembic/migrations/versions/20250812_1449_c828aa92b108_add_sso_linking_preference_to_users.py
  app/api/v1/admin/models.py
  app/api/v1/api.py
  app/api/v1/endpoints/auth.py
  app/api/v1/endpoints/sso.py
  app/auth/__init__.py
  app/auth/sso/__init__.py
  app/auth/sso/base_provider.py
  app/auth/sso/exceptions.py
  app/auth/sso/providers.py
  app/core/config.py
  app/core/error_handling.py
  app/core/response_models.py
  app/crud/user.py
  app/models/models.py
  app/schemas/user.py
  app/services/sso_service.py
  docker/.env.example
  docker/README_SSO.md
  docker/docker-compose.yml
  docs/SSO_QUICK_START.md
  docs/SSO_SETUP_GUIDE.md
  docs/SSO_TECHNICAL_OVERVIEW.md
  frontend/src/App.js
  frontend/src/components/adapters/PageHeader.js
  frontend/src/components/admin/AdminHeader.js
  frontend/src/components/admin/AdminLayout.js
  frontend/src/components/admin/AdminSidebar.js
  frontend/src/components/auth/GitHubLinkModal.js
  frontend/src/components/auth/ProtectedRoute.js
  frontend/src/components/auth/SSOCallback.js
  frontend/src/components/auth/SSOConflictModal.js
  frontend/src/components/layout/PageHeader.js
  frontend/src/components/medical/StatusBadge.js
  frontend/src/components/medical/base/BaseMedicalCard.js
  frontend/src/components/navigation/NavigationWrapper.js
  frontend/src/config/navigation.config.js
  frontend/src/contexts/AuthContext.js
  frontend/src/hooks/useApi.js
  frontend/src/hooks/useAuth.js
  frontend/src/hooks/useMedicalData.js
  frontend/src/pages/Dashboard.js
  frontend/src/pages/admin/AdminSettings.css
  frontend/src/pages/admin/AdminSettings.js
  frontend/src/pages/admin/SystemHealth.js
  frontend/src/pages/auth/Login.js
  frontend/src/pages/medical/Procedures.js
  frontend/src/services/api/adminApi.js
  frontend/src/services/api/baseApi.js
  frontend/src/services/api/index.js
  frontend/src/services/auth/simpleAuthService.js
  frontend/src/styles/pages/Login.css
  frontend/src/utils/authUtils.js
  frontend/src/utils/secureStorage.js
Labels: enhancement

#186 fix: Pin Python base image to slim-bookworm
  docker/Dockerfile
Labels: bug

#188 Custom report tool
  CUSTOM_REPORT_GENERATION_DESIGN.md
  alembic/migrations/versions/20250815_1624_22a36efc4d79_add_report_templates_and_audit_tables.py
  alembic/migrations/versions/20250815_1635_42b59974972e_merge_custom_reports_with_main.py
  app/api/deps.py
  app/api/v1/api.py
  app/api/v1/endpoints/custom_reports.py
  app/api/v1/endpoints/patients.py
  app/core/database.py
  app/models/models.py
  app/schemas/custom_reports.py
  app/services/auth.py
  app/services/custom_report_pdf_generator.py
  app/services/custom_report_service.py
  frontend/src/App.js
  frontend/src/components/reports/CategoryTabs.js
  frontend/src/components/reports/RecordSelector.js
  frontend/src/components/reports/TemplateManager.js
  frontend/src/components/reports/index.js
  frontend/src/config/navigation.config.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useCustomReports.js
  frontend/src/hooks/useReportTemplates.js
  frontend/src/pages/reports/ReportBuilder.js
  frontend/src/services/api/index.js
Labels: enhancement

#189 Fix: Refactor event handling in FamilyHistoryCard
  frontend/src/components/medical/family-history/FamilyHistoryCard.js
  frontend/src/pages/medical/FamilyHistory.js
Labels: bug

#196 Enhance SSO provider functionality and logging
  CUSTOM_REPORT_GENERATION_DESIGN.md
  app/auth/sso/providers.py
  app/core/config.py
Labels: bug

#201 Enhance authentication and error handling in API and frontend components
  app/api/deps.py
  frontend/src/contexts/AppContext.js
  frontend/src/contexts/AuthContext.js
  frontend/src/services/api/index.js
Labels: bug

#202 Fix: Await token retrieval in error logging and logout methods
  app/core/config.py
  frontend/src/services/auth/simpleAuthService.js
Labels: bug

#206 Small screen form bug
  frontend/src/App.js
  frontend/src/components/medical/BaseMedicalForm.js
  frontend/src/utils/medicalFormFields.js
Labels: bug

#207 Screen hang bug
  app/core/config.py
  frontend/src/App.js
  frontend/src/components/medical/BaseMedicalForm.js
  frontend/src/components/medical/MantineMedicalForm.js
  frontend/src/pages/TestMedicationForm.js
  frontend/src/pages/medical/Medication.js
Labels: bug

#210 Improved practitioner specalties
  app/api/v1/endpoints/practitioner.py
  frontend/src/components/medical/BaseMedicalForm.js
  frontend/src/components/medical/MantinePractitionerForm.js
  frontend/src/components/medical/practitioners/PractitionerFormWrapper.js
  frontend/src/config/medicalSpecialties.js
  frontend/src/utils/medicalFormFields.js
Labels: enhancement
